spring.application.name=gymsystem

# --- 1. MySQL \u8CC7\u6599\u5EAB\u9023\u7DDA\u8A2D\u5B9A ---
# (\u8ACB\u78BA\u8A8D MySQL \u88E1\u9762\u5DF2\u7D93\u6709 CREATE DATABASE gymsystem; \u7684\u7A7A\u8CC7\u6599\u5EAB)
spring.datasource.url=jdbc:mysql://localhost:3306/gymsystem?serverTimezone=Asia/Taipei&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
spring.datasource.username=root
# TODO: \u9019\u88E1\u8ACB\u6539\u6210\u60A8\u672C\u6A5F MySQL \u7684\u5BC6\u78BC\uFF01
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# --- 2. Hibernate \u8A2D\u5B9A (\u555F\u52D5\u6642\u6703\u81EA\u52D5\u5E6B\u6211\u5011\u5EFA\u51FA\u6240\u6709\u7684\u8CC7\u6599\u8868) ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# --- 3. Thymeleaf \u6A21\u677F\u5F15\u64CE\u8A2D\u5B9A ---
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html